server.port=8080
spring.application.name=main-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-main
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none

# ????????????? ???? ?? schema.sql
spring.sql.init.mode=always

# ?????? ?? ?????? ??????????
stats-server.url=http://localhost:9090

logging.level.org.springframework.web.client.RestTemplate=DEBUG

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=TRACE