DROP TABLE IF EXISTS events_compilations CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rating_events CASCADE;

DROP TYPE IF EXISTS event_state CASCADE;
DROP TYPE IF EXISTS request_state CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(250) NOT NULL,
	email varchar(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation varchar(2000) NOT NULL,
	category_id BIGINT NOT NULL REFERENCES categories(id),
	confirmed_requests BIGINT,
	created_on timestamp NOT NULL,
	description varchar(7000) NOT NULL,
	event_date timestamp NOT NULL,
	initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	paid bool NOT NULL,
	participant_limit INTEGER NOT NULL,
	published_on timestamp,
	request_moderation bool NOT NULL,
	state varchar(10) NOT NULL CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
	title varchar(120) NOT NULL,
	lat float NOT NULL,
    lon float NOT NULL,
	views BIGINT
);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_event_id ON events(id, initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_state_categore_event_date ON
        events(initiator_id, state, category_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_id_state ON events(id, state);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status varchar(10) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED', 'REJECTED')),
    CONSTRAINT uq_request_user_event UNIQUE (event_id, requester_id)
);

CREATE INDEX IF NOT EXISTS idx_participation_requests_requester_id ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_event_id ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_id_requester_id ON participation_requests(id, requester_id);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned bool NOT NULL,
    title varchar(50) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations(pinned);

CREATE TABLE IF NOT EXISTS events_compilations (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_events_compilations_compilation_id ON events_compilations(compilation_id);
CREATE INDEX IF NOT EXISTS idx_events_compilations_events_id ON events_compilations(event_id);
CREATE INDEX IF NOT EXISTS idx_events_compilations_compilation_events_id
    ON events_compilations(compilation_id, event_id);

CREATE TABLE IF NOT EXISTS rating_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    value SMALLINT NOT NULL CHECK (value IN (1, -1)),
    created timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rating_events_event_id ON rating_events(event_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rating_events_event_user_id ON rating_events(event_id, user_id);