DROP TYPE IF EXISTS event_state;
DROP TYPE IF EXISTS request_state;
CREATE TYPE event_state AS ENUM ('PENDING', 'PUBLISHED', 'CANCELED');
CREATE TYPE request_status AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED');

CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(250) NOT NULL,
	email varchar(254) UNIQUE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS categories (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_categories_name ON categories("name");

CREATE TABLE IF NOT EXISTS events (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation varchar(2000) NOT NULL,
	category_id bigint NOT NULL REFERENCES categories(id),
	confirmed_requests bigint,
	created_on timestamp NOT NULL,
	description varchar(7000) NOT NULL,
	event_date timestamp NOT NULL,
	initiator_id bigint NOT NULL REFERENCES users(id),
	paid bool NOT NULL,
	participant_limit int32 NOT NULL,
	published_on timestamp,
	request_moderation bool NOT NULL,
	state event_state NOT NULL,
	title varchar(120) NOT NULL UNIQUE,
	views bigint
);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_event_id ON events(id, initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_state_categore_event_date ON
        events(initiator_id, state, category_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_id_state ON events(id, state);


CREATE TABLE IF NOT EXISTS locations (
    event_id bigint NOT NULL,
    lat float NOT NULL,
    lon float NOT NULL,
    CONSTRAINT locations_pk PRIMARY KEY (event_id),
	CONSTRAINT events_locations_fk FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp NOT NULL,
    event_id bigint NOT NULL REFERENCES events(id),
    requester_id bigint NOT NULL REFERENCES users(id),
    status request_status NOT NULL,
    CONSTRAINT uq_request_user_event UNIQUE (event_id, requester_id)
);

CREATE INDEX IF NOT EXISTS idx_participation_requests_requester_id ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_event_id ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_participation_requests_id_requester_id ON participation_requests(id, requester_id);

CREATE TABLE IF NOT EXISTS compilations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned bool NOT NULL,
    title varchar(50) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations(pinned);
CREATE INDEX IF NOT EXISTS idx_compilations_title ON compilations(title);

CREATE TABLE IF NOT EXISTS events_compilations (
    compilation_id bigint REFERENCES compilations(id) ON DELETE CASCADE,
    event_id bigint REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_events_compilations_compilation_id ON events_compilations(compilation_id);
CREATE INDEX IF NOT EXISTS idx_events_compilations_events_id ON events_compilations(event_id);
CREATE INDEX IF NOT EXISTS idx_events_compilations_compilation_events_id
    ON events_compilations(compilation_id, event_id);