services:
  stats-server:
    build: stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=stats
      - POSTGRES_USER=stats
      - POSTGRES_DB=ewm-stats
    volumes:
      - ./stats/stats-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
      - STATS_SERVER_URI=http://stats-server:9090
      - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=ewm-main